### ISSUE TITLE
lost gssapi.raw.ext_cred_store module

### ISSUE THREAD

**Issue by shm007g** [krbcontext/python-krbcontext#22]
when i use krbContext to download hdfs files in yarn cluster as below:

```
with krbContext(using_keytab=True, principal=principal, keytab_file=keytab_path):
            client = KerberosClient('http://{0}:50070'.format(server))
            client.download(os.path.join(HDFS_ROOT, hdfs_path), local_path, overwrite=True)
```
error happens here:
```
 with krbContext(using_keytab=True, principal=principal, keytab_file=keytab_path):
  File "/usr/local/anaconda3/lib/python3.5/site-packages/krbcontext/context.py", line 281, in __enter__
    self._prepare_context()
  File "/usr/local/anaconda3/lib/python3.5/site-packages/krbcontext/context.py", line 271, in _prepare_context
    self.init_with_keytab()
  File "/usr/local/anaconda3/lib/python3.5/site-packages/krbcontext/context.py", line 165, in init_with_keytab
    creds = gssapi.creds.Credentials(**creds_opts)
  File "/usr/local/anaconda3/lib/python3.5/site-packages/gssapi/creds.py", line 64, in __new__
    store=store)
  File "/usr/local/anaconda3/lib/python3.5/site-packages/gssapi/creds.py", line 140, in acquire
    raise NotImplementedError("Your GSSAPI implementation does "
NotImplementedError: Your GSSAPI implementation does not have support for manipulating credential stores
```
then i google it, i found this in gssapi code
![image](https://user-images.githubusercontent.com/16999665/34146073-8cfd8792-e4d3-11e7-8c99-0e7cb0feacff.png)
then i search for `rcred_cred_store `
![image](https://user-images.githubusercontent.com/16999665/34146171-e1184006-e4d3-11e7-8a11-e95c34fe4a6d.png)
then i search for `import_gssapi_extension`
![image](https://user-images.githubusercontent.com/16999665/34146124-b27d0c7c-e4d3-11e7-8a2b-0b3658dabc4d.png)

# OMG, lost one module!!!

```
>>> import gssapi
>>> import gssapi.raw
>>> import gssapi.raw.ext_cred_store
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'gssapi.raw.ext_cred_store'
```

**Comment by tkdchen** [comment]
What version of python-gssapi are you using?

**Comment by tkdchen** [comment]
Both latest version `gssapi 1.5.1` and `python2-gssapi-1.3.0-1.fc27.x86_64` work well with `import gssapi.raw.ext_cred_store`.

No response from reporter. There is no additional information about this issue.
