### ISSUE TITLE
setup wheels fails in python 3.6.2 centos linux 7

### ISSUE THREAD

**Issue by PeteW** [krbcontext/python-krbcontext#30]
Using a pristine virtual environment 
```
python -V
Python 3.6.2 :: Continuum Analytics, Inc.
cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)
```

```
Building wheels for collected packages: krbcontext
  Running setup.py bdist_wheel for krbcontext ... error
  Complete output from command /opt/miniconda2/envs/kerberosexp/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9eec7gwe/krbcontext/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp6m15r8fypip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/krbcontext
  copying krbcontext/__init__.py -> build/lib/krbcontext
  copying krbcontext/context.py -> build/lib/krbcontext
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/krbcontext
  copying build/lib/krbcontext/__init__.py -> build/bdist.linux-x86_64/wheel/krbcontext
  copying build/lib/krbcontext/context.py -> build/bdist.linux-x86_64/wheel/krbcontext
  running install_egg_info
  running egg_info
  writing krbcontext.egg-info/PKG-INFO
  writing dependency_links to krbcontext.egg-info/dependency_links.txt
  writing requirements to krbcontext.egg-info/requires.txt
  writing top-level names to krbcontext.egg-info/top_level.txt
  reading manifest file 'krbcontext.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'krbcontext.egg-info/SOURCES.txt'
  Copying krbcontext.egg-info to build/bdist.linux-x86_64/wheel/krbcontext-0.10-py3.6.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-9eec7gwe/krbcontext/setup.py", line 71, in <module>
      'Topic :: System :: Systems Administration',
    File "/opt/miniconda2/envs/kerberosexp/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/miniconda2/envs/kerberosexp/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/opt/miniconda2/envs/kerberosexp/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/opt/miniconda2/envs/kerberosexp/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 232, in run
      self.distinfo_dir)
    File "/opt/miniconda2/envs/kerberosexp/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 399, in egg2dist
      distribution=self.distribution)
    File "/opt/miniconda2/envs/kerberosexp/lib/python3.6/site-packages/wheel/metadata.py", line 176, in pkginfo_to_dict
      new_requirements = sorted(convert_requirements(requirements))
    File "/opt/miniconda2/envs/kerberosexp/lib/python3.6/site-packages/wheel/metadata.py", line 231, in convert_requirements
      parsed_requirement = pkg_resources.Requirement.parse(req)
    File "/opt/miniconda2/envs/kerberosexp/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2974, in parse
      req, = parse_requirements(s)
  ValueError: not enough values to unpack (expected 1, got 0)

  ----------------------------------------
  Failed building wheel for krbcontext
  Running setup.py clean for krbcontext
Failed to build krbcontext
```

**Comment by PeteW** [comment]
Disregard. The issue seems to be related to a spurious version of pip.
Installing using a downgraded version of pip along with the `--no-cache-dir` option works around the issue.
