### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by rsaggino** [krbcontext/python-krbcontext#36]
Basically, this is the same issue as #30  

```
pip3 -V
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
pip 20.3.1 from /home/mhj/.local/lib/python3.6/site-packages/pip (python 3.6)
```

This is the error:

```
Defaulting to user installation because normal site-packages is not writeable
Processing ./krbcontext-0.10.tar.gz
Requirement already satisfied: gssapi in /home/mhj/.local/lib/python3.6/site-packages (from krbcontext==0.10) (1.6.12)
Requirement already satisfied: decorator in /home/mhj/.local/lib/python3.6/site-packages (from gssapi->krbcontext==0.10) (4.4.2)
Building wheels for collected packages: krbcontext
  Building wheel for krbcontext (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-1t45edxl/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-1t45edxl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-hf59qy8_
       cwd: /tmp/pip-req-build-1t45edxl/
  Complete output (50 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/krbcontext
  copying krbcontext/context.py -> build/lib/krbcontext
  copying krbcontext/__init__.py -> build/lib/krbcontext
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/krbcontext
  copying build/lib/krbcontext/context.py -> build/bdist.linux-x86_64/wheel/krbcontext
  copying build/lib/krbcontext/__init__.py -> build/bdist.linux-x86_64/wheel/krbcontext
  running install_egg_info
  running egg_info
  writing krbcontext.egg-info/PKG-INFO
  writing dependency_links to krbcontext.egg-info/dependency_links.txt
  writing requirements to krbcontext.egg-info/requires.txt
  writing top-level names to krbcontext.egg-info/top_level.txt
  reading manifest file 'krbcontext.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'krbcontext.egg-info/SOURCES.txt'
  Copying krbcontext.egg-info to build/bdist.linux-x86_64/wheel/krbcontext-0.10.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-1t45edxl/setup.py", line 71, in <module>
      'Topic :: System :: Systems Administration',
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 257, in run
      self.distinfo_dir)
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 427, in egg2dist
      distribution=self.distribution)
    File "/usr/lib/python3/dist-packages/wheel/metadata.py", line 177, in pkginfo_to_dict
      new_requirements = sorted(convert_requirements(requirements))
    File "/usr/lib/python3/dist-packages/wheel/metadata.py", line 234, in convert_requirements
      parsed_requirement = pkg_resources.Requirement.parse(req)
    File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2988, in parse
      req, = parse_requirements(s)
  ValueError: not enough values to unpack (expected 1, got 0)
  ----------------------------------------
  ERROR: Failed building wheel for krbcontext
  Running setup.py clean for krbcontext
Failed to build krbcontext
Installing collected packages: krbcontext
    Running setup.py install for krbcontext ... done
  DEPRECATION: krbcontext was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Successfully installed krbcontext-0.10

```

**Comment by tkdchen** [comment]
Can you still reproduce this issue? I tried with centos:7, however I can't reproduce this issue in my environment.

A pre-built wheel distribution was missed in the PyPI for version 0.10. This will be fixed in next version soon.
